# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 23:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('article_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('article_date', models.DateTimeField(verbose_name='Дата и время')),
                ('article_likes', models.IntegerField(default=0)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Видео')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-article_date'],
                'verbose_name': 'статьи',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
